### ISSUE TITLE
Magazine In 1889 Asked Women Why They Are Single

### ISSUE THREAD

**Issue by lalalallalallalalalalal** [acearchive/artifact-submissions#128]
### Context and significance

A magazine in 1889 asked single women to give their best answers to the question “Why are you a spinster”. The answers show how confident these women were even though they went against amatonormativity. 

### Sources

https://www.boredpanda.com/victorian-magazine-women-reasons-single-spinsters/

https://x.com/DigiVictorian/status/964842367508516864?s=20&t=UJgqWhfl4UXYdTkeKlr8_A

### Content warnings

Sexism

**Comment by frawleyskid** [comment]
Thanks for your submission! It's live [here](https://acearchive.lgbt/artifacts/tit-bits-the-spinsters-prize/).
