### ISSUE TITLE
Monograph on asexuality and the media

### ISSUE THREAD

**Issue by vipurple** [acearchive/artifact-submissions#18]
### Context and significance

In this monograph we study the emergence of counter-hegemonic narratives in
cyberspace. Counter-hegemonic narratives are those that are produced by groups
that do not feel represented in the media or that create a discourse that goes against
what is present in the hegemonic media, such as the asexuality narrative. The
hypothesis that drives us is that this emergence takes place as a result of the
process of mediatization and, in it, cyberspace. To this end, we begin by
contextualizing what is narrative and its importance for identity formation, as well as
exploring the theoretical framework of mediatization and the new technological
ambience, using cyberspace as the environment in which counter-hegemonic
narratives rise. This is a case study, understood here as a research method that
involves a detailed and in-depth examination of an object as well as its related
contextual conditions. The object of study has ten excerpts that allow us to identify
the evolution of the narrative of asexuality in the media.

### Sources

https://repositorio.unisc.br/jspui/handle/11624/2744

### People

Vitória Carvalho Rocho

### Identities

Asexuality

### Years

2020

**Comment by frawleyskid** [comment]
Hey! Thanks for your submission!

Unfortunately, Ace Archive isn't really intended as a platform for sharing new research. However, I do recommend checking out [Sennkestra's asexuality bibliography](https://www.zotero.org/groups/950137/asexual_research) if you haven't already. I suspect they would be happy to include this!

— Frawley
