### ISSUE TITLE
Nonfiction Book List

### ISSUE THREAD

**Issue by tatianaluz** [acearchive/artifact-submissions#20]
### Context and significance

I think the archive should include a lists of non-fiction book publications. While there is an increase in content being published in recent years, there does not appear to be a centralized location listing these publications. Such a list would be useful, and easier, for those looking for publications to do research. It may become more difficult to create this list as more time goes one and more publications are released. There may also be books about asexuality that date back prior to the 2000s but do not often come up in reach on asexual history. The list should include titles, authors, publication years, and ISBNs (where possible).

### Sources

Below is an example of some of the nonfiction books the exist regarding asexuality. This is not a full list, as this is only a list from my local library system, and items may become lost as books are removed from circulations. This will make is harder for people to know of the existence of such publications.

https://morristowntwp.aspendiscovery.org/Search/Results?lookfor=asexuality&searchIndex=Keyword&filter[]=literary_form%3A%22Non+Fiction%22&sort=relevance&view=list&searchSource=local

**Comment by frawleyskid** [comment]
Awesome! If you do decide to put something like that together, I would love to include it in the archive. Let me know what you come up with!

**Comment by frawleyskid** [comment]
This looks excellent! I'll go ahead and add it to the archive!

Just a quick question: How do you want to be attributed as the person who put this together? Can be a full name, just a first name, a handle, whatever you prefer!

**Comment by frawleyskid** [comment]
Done! It's live on the site [here](https://acearchive.lgbt/artifacts/t-pagan-guerra-library-of-asexual-nonfiction/)!

Thank you so much for your help, and happy pride month!
